### ISSUE TITLE
Issue with add_page() function

### ISSUE THREAD

**Issue by ElephontDearie** [CandaceJWilliams/python-journal#1]
#new py user here

add_page() has add_content(title) in its last line
This gives:
  “TypeError: add_content() takes 0 positional arguments but 1 was given”

**Comment by jeffmilam** [comment]
Same error for me.  When I comment out the add page function, I also get the following issue: 

What's your name?  jeff
Traceback (most recent call last):
  File "journal_test.py", line 107, in <module>
    author = input("What's your name?  ")
  File "<string>", line 1, in <module>
NameError: name 'jeff' is not defined

**Comment by mpeseke** [comment]
The error here is because the add_page() function is calling the add_content(title) function, but it is feeding in the variable "title". The add_content() function doesn't accept variables, but we still need the add_page() function, as well.
